pipeline:
  identifier: Pipeline
  name: Converter_Name
  orgIdentifier: default
  projectIdentifier: rssplay
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: Build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: runstep0
                  name: RunStep0
                  spec:
                    command: Run Build Stage
                    shell: Sh
                  type: Run
          platform:
            arch: Arm64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        when:
          pipelineStatus: Success
    - stage:
        identifier: staticcodeanalysis
        name: Static Code Analysis
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: runstep0
                  name: RunStep0
                  spec:
                    command: echo 'Run Static Code Analysis'
                    shell: Sh
                  type: Run
          platform:
            arch: Arm64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        when:
          pipelineStatus: Success
    - parallel:
        - stage:
            identifier: testonwindows
            name: Test On Windows
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "run-tests.bat"
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: testonlinux
            name: Test On Linux
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "run-tests.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: run-tests.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: testonlinuxnew
            name: Test On Linux New
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "run-tests.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: run-tests.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep2
                      name: RunStep2
                      spec:
                        command: run-tests.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
    - parallel:
        - stage:
            identifier: testonwindowsnew
            name: Test On Windows New
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "run-tests.bat"
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: testonlinuxnew1
            name: Test On Linux New
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "run-tests.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: run-tests.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: testonlinuxnewdoc
            name: Test On Linux New DOC
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "run-tests.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: run-tests.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep2
                      name: RunStep2
                      spec:
                        command: run-tests.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              condition: <+pipeline.branch> == "branch" && <+pipeline.branch> == "master" && <+pipeline.branch> == ";"
              pipelineStatus: Success
    - stage:
        identifier: unittests
        name: Unit Tests
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: runstep0
                  name: RunStep0
                  spec:
                    command: echo 'Run Unit Tests'
                    shell: Sh
                  type: Run
          platform:
            arch: Arm64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        when:
          pipelineStatus: Success
    - stage:
        identifier: acceptancetests
        name: Acceptance Tests
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: runstep0
                  name: RunStep0
                  spec:
                    command: echo 'Run Acceptance Tests'
                    shell: Sh
                  type: Run
          platform:
            arch: Arm64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        when:
          pipelineStatus: Success
  variables:
    - name: git_commit_message
      type: String
      value: default
    - name: git_commit_diff
      type: String
      value: default
    - name: git_commit_author
      type: String
      value: default
    - name: git_commit_author_name
      type: String
      value: default
    - name: git_commit_author_email
      type: String
      value: default
