pipeline:
  identifier: Pipeline
  name: Converter_Name
  orgIdentifier: default
  projectIdentifier: rssplay
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
    - parallel:
        - stage:
            identifier: linting
            name: Linting
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "Running linter on ${OS} with ${Browser}"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: |
                          python3 -m flake8 my_code/
                          # To_Do_Change elseif(OS==Windows)batflake8 my_code\\
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            strategy:
              matrix:
                Browser:
                  - Chrome
                  - Firefox
                  - Safari
                OS:
                  - Linux
                  - Windows
                  - Mac
                exclude:
                  - Browser: Safari
                    OS: Linux
                  - Browser: Firefox
                    OS: windows
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: build
            name: Build
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "Running linter on ${OS} with ${Browser}"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: |
                          python3 -m flake8 my_code/
                          # To_Do_Change elseif(OS==Windows)batflake8 my_code\\
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep2
                      name: RunStep2
                      spec:
                        command: echo "Building on ${OS} with ${Browser}"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep3
                      name: RunStep3
                      spec:
                        command: |
                          # To_Do_Change elseif(OS==Windows)batflake8 my_code\\
                          ./build.sh
                          # To_Do_Change elseif(OS==Windows)batbuild.batelseif(OS==Mac)
                          ./build.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            strategy:
              matrix:
                Browser:
                  - Chrome
                  - Firefox
                  - Safari
                OS:
                  - Linux
                  - Windows
                  - Mac
                exclude:
                  - Browser: Safari
                    OS: Linux
                  - Browser: Firefox
                    OS: windows
            type: CI
            when:
              pipelineStatus: Success
    - parallel:
        - stage:
            identifier: linuxchrome
            name: Linux Chrome
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "Running on Linux with Chrome"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: ./run_tests.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep2
                      name: RunStep2
                      spec:
                        command: ./deploy.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: windowsfirefox
            name: Windows Firefox
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "Running on Linux with Chrome"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: ./run_tests.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep2
                      name: RunStep2
                      spec:
                        command: ./deploy.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep3
                      name: RunStep3
                      spec:
                        command: echo "Running on Windows with Firefox"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep4
                      name: RunStep4
                      spec:
                        command: echo "run_tests.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep5
                      name: RunStep5
                      spec:
                        command: echo "deploy.bat"
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
        - stage:
            identifier: macsafari
            name: Mac Safari
            spec:
              cloneCodebase: false
              execution:
                steps:
                  - step:
                      identifier: runstep0
                      name: RunStep0
                      spec:
                        command: echo "Running on Linux with Chrome"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep1
                      name: RunStep1
                      spec:
                        command: ./run_tests.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep2
                      name: RunStep2
                      spec:
                        command: ./deploy.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep3
                      name: RunStep3
                      spec:
                        command: echo "Running on Windows with Firefox"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep4
                      name: RunStep4
                      spec:
                        command: echo "run_tests.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep5
                      name: RunStep5
                      spec:
                        command: echo "deploy.bat"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep6
                      name: RunStep6
                      spec:
                        command: echo "Running on Mac with Safari"
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep7
                      name: RunStep7
                      spec:
                        command: ./run_tests.sh
                        shell: Sh
                      type: Run
                  - step:
                      identifier: runstep8
                      name: RunStep8
                      spec:
                        command: ./deploy.sh
                        shell: Sh
                      type: Run
              platform:
                arch: Arm64
                os: Linux
              runtime:
                spec: {}
                type: Cloud
            type: CI
            when:
              pipelineStatus: Success
